### ISSUE TITLE
ZipDL method creates zip with an additional folder

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-git2s3#10]
when the repo contents are in a sub-folder integrations with things like CodeDeploy do not work.

**Comment by ranjit009** [comment]
Yes exactly that's the only problem with this template.

**Comment by jaymccon** [comment]
@ranjit009 the workaround for this is to use the GitPull method, described on page 8 of the [deployment guide](https://s3.amazonaws.com/quickstart-reference/git2s3/latest/doc/git-to-amazon-s3-using-webhooks.pdf), which does not have this issue.

**Comment by ranjit009** [comment]
@jaymccon Thanks
