### ISSUE TITLE
JSON error when using ZipDl

### ISSUE THREAD

**Issue by cjunge-work** [aws-quickstart/quickstart-git2s3#11]
When I use the ZipDl endpoint with a Bitbucket webhook I get the following error:

```json
{
"message": "Could not parse request body into json: Unexpected character ('}' (code 125)): was expecting double-quote to start field name\n at [Source: [B@2ef71fad; line: 60, column: 6]"
}
```

It appears to be an error from API Gateway, but the format of the message is valid JSON, and resubmitting the same payload to the GitPull endpoint works as expected.

I can send via email an example payload, configured endpoints and my tweaked template.

**Comment by jaymccon** [comment]
@cjunge-work 

If possible can you provide the payload and template as a comment on this issue ? if there's anything you don't want to share publicly please redact it first.

Thanks!

**Comment by cjunge-work** [comment]
Changed how we're doing this, so no longer an issue for us.
