### ISSUE TITLE
“'full_name': KeyError” in GitPullLambda when processing BitBucket WebHook request

### ISSUE THREAD

**Issue by dirkweinhardt** [aws-quickstart/quickstart-git2s3#14]
Full error message:

```
'full_name': KeyError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 142, in lambda_handler
repo_name = event['body-json']['repository']['full_name']
KeyError: 'full_name'

```
BitBucket POSTs a body like the one shown below. To me it seems the repo name would have to be read from `event['body-json']['repository']['fullName']` (no underscore, upper-case N)

```
{
  "actor": {
    "username": "Joe.Average",
    "displayName": "Average, Joe"
  },
  "repository": {
    "scmId": "git",
    "project": {
      "key": "~JOE.AVERAGE",
      "name": "Average, Joe"
    },
    "slug": "demo",
    "links": {
      "self": [
        {
          "href": "https:\/\/bitbucket.exmaple.com\/users\/joe.average\/repos\/demo\/browse"
        }
      ]
    },
    "public": false,
    "fullName": "~JOE.AVERAGE\/demo",
    "ownerName": "~JOE.AVERAGE",
    "owner": {
      "username": "~JOE.AVERAGE",
      "displayName": "~JOE.AVERAGE"
    }
  },
  "push": {
    "changes": [
      {
        "created": false,
        "closed": false,
        "old": {
          "type": "branch",
          "name": "master",
          "target": {
            "type": "commit",
            "hash": "cd193abca3fc51336de56e75c0d3237a01d4e58d"
          }
        },
        "new": {
          "type": "branch",
          "name": "master",
          "target": {
            "type": "commit",
            "hash": "24dc6ec44645411b5b6ee7e925c66e740ada3ba9"
          }
        }
      }
    ]
  }
}
```

**Comment by jaymccon** [comment]
@dirkweinhardt I've been unable to replicate this, my bitbucket cloud account is not populating webhooks, but I've put a potential fix in place with https://github.com/aws-quickstart/quickstart-git2s3/commit/b3a1d04a9ec3c82138398d89b3d5d88ecbba810d.

Can you please let me know if this has addressed your issue ?

**Comment by dirkweinhardt** [comment]
@jaymccon, I am currently struggling getting the BitBucket Webhooks to fire at all. I will keep trying and let you know. However, the changes look reasonable to me.

**Comment by jaymccon** [comment]
I managed to get my bitbucket cloud webhooks operational, but the json I receive does not match the format you are getting, it has `full_name` in the repository section. 

@dirkweinhardt - can you confirm which version of bitbucket you are running ?

```
...
"repository": {
    "scm": "git",
    "website": "",
    "name": "reponame",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/username/reponame"
      },
      "html": {
        "href": "https://bitbucket.org/username/reponame"
      },
      "avatar": {
        "href": "https://bitbucket.org/username/reponame/avatar/123/"
      }
    },
    "full_name": "username/reponame",
    "owner": {
      "username": "username",
      "type": "user",
      "display_name": "My Name",
      "uuid": "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx}",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/username"
        },
        "html": {
          "href": "https://bitbucket.org/username/"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/username/avatar/132/"
        }
      }
    },
...
```

**Comment by dirkweinhardt** [comment]
@jaymccon, our BitBucket version is “Atlassian Bitbucket v5.3.2”. AFAIK it's an on-promise install.

**Comment by jaymccon** [comment]
thanks @dirkweinhardt, I haven't been able to get an equivalent veriosn running, but my guess is that #14 solves this, please feel free to re-open if that's not the case.

**Comment by sathyajackson** [comment]
Hi All,

I am facing the same problem as #14. We have an in-house bitbucket and trying to integrate the webhook with AWS service. While troubleshooting with AWS we found that the payload from the bitbucket is completely different from the one which the lambda function expects. 

Lambda error : - 

'project': KeyError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 158, in lambda_handler
full_name = event['body-json']['project']['path_with_namespace']
KeyError: 'project'

Payload (json body) sent by bitbucket.

{"eventKey":"repo:refs_changed","date":"2018-10-30T12:06:21+0000","actor":{"name":"sathyanarayanan.ramamurthy","emailAddress":"Sathyanarayanan.Ramamurthy@csscorp.com","id":269,"displayName":"Sathyanarayanan Ramamurthy","active":true,"slug":"sathyanarayanan.ramamurthy","type":"NORMAL"},"repository":{"slug":"demo-aws-codedeploy","id":361,"name":"demo-aws-codedeploy","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"IT","id":154,"name":"Internal Testing","public":false,"type":"NORMAL"},"public":false},"changes":[{"ref":{"id":"refs/heads/master","displayId":"master","type":"BRANCH"},"refId":"refs/heads/master","fromHash":"ebb01dc966228ea93cc6036d9efe94f56480b89d","toHash":"3f8371baa548e516eee3d68b09fb4f608ff42920","type":"UPDATE"}]}

**Comment by sathyajackson** [comment]
{
"eventKey":"repo:refs_changed",
"date":"2018-10-30T12:06:21+0000",
"actor":{
"name":"sathyanarayanan.ramamurthy",
"emailAddress":"Sathyanarayanan.Ramamurthy@csscorp.com",
"id":269,
"displayName":"Sathyanarayanan Ramamurthy",
"active":true,
"slug":"sathyanarayanan.ramamurthy",
"type":"NORMAL"
},
"repository":{
"slug":"demo-aws-codedeploy",
"id":361,
"name":"demo-aws-codedeploy",
"scmId":"git",
"state":"AVAILABLE",
"statusMessage":"Available",
"forkable":true,
"project":{
"key":"IT",
"id":154,
"name":"Internal Testing",
"public":false,
"type":"NORMAL"
},
"public":false
},
"changes":[
{
"ref":{
"id":"refs/heads/master",
"displayId":"master",
"type":"BRANCH"
},
"refId":"refs/heads/master",
"fromHash":"ebb01dc966228ea93cc6036d9efe94f56480b89d",
"toHash":"3f8371baa548e516eee3d68b09fb4f608ff42920",
"type":"UPDATE"
}
]
}
