### ISSUE TITLE
unable to connect to Gitlab

### ISSUE THREAD

**Issue by user-muthu** [aws-quickstart/quickstart-git2s3#31]
I see the lambda was invoked in the cloud watch logs, however it is failed with the following error. I need some help to resolve this issue.

failed to resolve address for git.xxxx.xxxxx.xxxxxxx.com: Name or service not known: GitError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 191, in lambda_handler
repo = create_repo(repo_path, remote_url, creds)
File "/var/task/lambda_function.py", line 69, in create_repo
repo = clone_repository(remote_url, repo_path, callbacks=creds)
File "/var/task/pygit2/__init__.py", line 263, in clone_repository
check_error(err)
File "/var/task/pygit2/errors.py", line 64, in check_error
raise GitError(message)
GitError: failed to resolve address for git.xxx.xxxx.xxxxxxx.com: Name or service not known

**Comment by jaymccon** [comment]
That error indicates that the lambda function was unable to resolve dns for `git.xxxx.xxxxx.xxxxxxx.com` are you able to verify that this address is resolvable from the internet ?

If the git server is inside a private vpc, have a look at https://aws.amazon.com/blogs/devops/using-custom-source-actions-in-aws-codepipeline-for-increased-visibility-for-third-party-source-control/ which provides support for a  git repo in a VPC's private subnet.
