### ISSUE TITLE
Upgrade CopyZips from Python 2.7 to 3.x

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-git2s3#46]
Python 2.7 is EOL in January 2020. We need to upgrade the CopyZips function prior to then.

**Comment by prganesan** [comment]
GitPullLambda,ZipDlLambda & DeleteBucketContents also use Python 2.7 . Will you be upgrading these to Python 3.7

**Comment by andrew-glenn** [comment]
@prganesan While we're modifying the template, we'll upgrade those to 3.x as well.
